# Site settings
title: Bash 指南
email: wdcszyyx@outlook.com
description: >
  A complete guide for newcomers and advanced users to correct usage and deep understanding of the bash shell language.
baseurl: ""
url: "https://learn-it-zh.github.io/"
twitter_username: lhunath
github_username:  lhunath

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-leap-day